package validate

const (
	userName         = "userName"
	passWord         = "passWord"
	nickName         = "nickName"
	email            = "email"
	failNotify       = "failNotify"
	name             = "name"
	intervalDuration = "intervalDuration"
	protocol         = "protocol"
	nextRuntime      = "nextRuntime"
	unitOfInterval   = "unitOfInterval"
	httpMethod       = "httpMethod"
	newPassWord      = "newPassWord"
	status           = "status"
	headers          = "headers"
	command          = "command"
	param            = "param"
	postType         = "postType"
	remark           = "remark"
	companyCode      = "companyCode"
	taskCode         = "taskCode"
	role             = "role"
)
